//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HR_PAYROLL_PROCESSING_SYSTEM.Master
{
    public partial class UserMasterUpdate
    {
    }
}
